In [38]:
import numpy as np
x=(1,2,3)
a=np.array([x,(6,5,6)])
b=np.array([(1.5,2,3),(4,5,6)],dtype = float)
print(type(x))

<class 'tuple'>


In [44]:
import pandas as pn
import numpy as np

df = pn.read_csv('/home/user/Documents/a.csv')

a = np.array([df['id'],df['Name '],df['cie1'],df['cie2'],df['cie3']])

print(a)
print(np.mean(a[0]))
print(np.min(a[0]))
print(np.max(a[0]))
print(np.sum(a[0]))
print(np.sin(a[0][0]))
print(a[0:1])

[[3 4 5 6]
 ['abc' 'xyz' 'lmn' 'opq']
 [23 15 22 30]
 [21 12 21 30]
 [22 10 29 26]]
4.5
3
6
18
0.1411200080598672
[[3 4 5 6]]


In [ ]:
import pandas as pn
import numpy as np

df = pn.read_csv('/home/user/Documents/a.csv')

a = np.array([df['id'],df['Name ']])